M48
; DRILL file {KiCad 7.0.1} date Thu Mar 23 12:40:09 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-23T12:40:09+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X134.99Y-84.926
X160.35Y-84.926
T2
X98.425Y-47.625
X98.425Y-125.095
X211.455Y-47.625
X211.455Y-125.095
T0
M30
