M48
; DRILL file {KiCad 7.0.1} date Sun Apr  9 10:37:19 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-09T10:37:19+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X98.425Y-47.625
X98.425Y-125.095
X211.455Y-47.625
X211.455Y-125.095
T0
M30
